FROM python:3.7-slim

RUN mkdir /opt/{{cookiecutter.app_name}}

RUN python -m pip install --upgrade pip

RUN python -m pip install poetry
WORKDIR /opt/{{cookiecutter.app_name}}

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry install --no-root -vvv


ENTRYPOINT ["poetry"]
